const shapeDefinitions = [
  { type: "One", label: "One", icon: "images/shapes/one.png" },
  { type: "T", label: "T", icon: "images/shapes/t.png" },
  { type: "L", label: "L", icon: "images/shapes/l.png" },
  { type: "LReverse", label: "L Reverse", icon: "images/shapes/l_reverse.png" },
  { type: "LSmall", label: "L Small", icon: "images/shapes/l_small.png" },
  { type: "Z", label: "Z", icon: "images/shapes/z.png" },
  { type: "ZReverse", label: "Z Reverse", icon: "images/shapes/z_reverse.png" },
  { type: "Square", label: "Square", icon: "images/shapes/square.png" },
  { type: "SquareLarge", label: "Square Large", icon: "images/shapes/square_large.png" },
  { type: "Rectangle", label: "Rectangle", icon: "images/shapes/rectangle.png" },
  { type: "Line", label: "Line", icon: "images/shapes/line.png" },
  { type: "LineMini", label: "Line Mini", icon: "images/shapes/line_mini.png" },
  { type: "LineSmall", label: "Line Small", icon: "images/shapes/line_small.png" },
  { type: "LineLong", label: "Line Long", icon: "images/shapes/line_long.png" },
  { type: "Cross", label: "Cross", icon: "images/shapes/cross.png" },
  { type: "Slash", label: "Slash", icon: "images/shapes/slash.png" },
  { type: "SlashMini", label: "Slash Mini", icon: "images/shapes/slash_mini.png" },
  { type: "Factory", label: "Factory", icon: "images/shapes/factory.png" },
  { type: "FactoryReverse", label: "Factory Reverse", icon: "images/shapes/factory_reverse.png" },
];
